DROP TABLE IF EXISTS listinginfo1;

CREATE TABLE listinginfo1(
bathrooms int,
bedrooms int,
beds int,
capacity int,
Headers varchar(200),
hometype varchar(200),
hostName varchar(200),
id int PRIMARY KEY,
longDescription varchar(200),
neighborhood varchar(200),
PrimTrait varchar(200),
secondTrait varchar(200),
tertTrait varchar(200),
Wifi boolean,
Laptop_friendly_workspace boolean,
Air_conditioning boolean,
Kitchen boolean,
Washer boolean,
Free_parking_on_premise boolean,
Iron boolean,
Essentials boolean,
Tv boolean,
Hot_water boolean,
Pool boolean,
Cooking_basics boolean,
Dishes_and_silverware boolean,
Refrigerator boolean,
Oven boolean,
Stove boolean,
Hangers boolean,
Shampoo boolean,
Extra_pillow_and_blanket boolean,
Carbon_monoxide_detector boolean,
Smoke_Detector boolean,
First_aid_kit boolean,
Bed_linens boolean,
Private_entrance boolean,
Elevator boolean,
Hot_tub boolean);

\COPY listinginfo1(Bathrooms, Bedrooms, Beds, capacity,  Headers, hometype, hostName, id, longDescription, neighborhood, PrimTrait, secondTrait, tertTrait, Wifi, Laptop_friendly_workspace, Air_conditioning, Kitchen, Washer, Free_parking_on_premise, Iron, Essentials, Tv, Hot_water, Pool, Cooking_basics, Dishes_and_silverware, Refrigerator, Oven, Stove, Hangers, Shampoo, Extra_pillow_and_blanket, Carbon_monoxide_detector, Smoke_Detector, First_aid_kit, Bed_linens, Private_entrance, Elevator, Hot_tub) FROM '/Users/spencerpierce/listinginfo-module1/listingData.csv' DELIMITER ',' CSV HEADER;